### ISSUE TITLE
Need help confirming if normal map is loaded correctly

### ISSUE THREAD

**Issue by jiunyen-ching** [apple/ml-hypersim#11]
Hi, I am trying to visualize a normal map from a scene but I am not sure if this is the correct way to do it as some parts appear missing/black and some parts appear brighter.

The details are as below:

- Image type: normal_world
- Scene: ai_001_001
- Camera traj: scene_cam_00
- Image: frame.0000
- Code:
```
import h5py
from PIL import Image

h5_path = "/home/personal/hypersim/ai_001_001/images/scene_cam_00_geometry_hdf5/"
frame = h5_path + "frame.0000.normal_world.hdf5"

with h5py.File(frame, "r") as f:    
    array = f["dataset"][:]
    img = Image.fromarray(array.astype('uint16'), 'RGB')
    img.show()
```
Output:
![image](https://user-images.githubusercontent.com/25114361/104121052-632be700-5376-11eb-8651-71a0a8f4d1de.png)

Hope to hear from you soon!

**Comment by mikeroberts3000** [comment]
Hi! The HDF5 file that you're loading contains floating point values in the range [-1,1]. I'm not sure exactly what happens when you attempt to convert such an array into an array of uint16 values, but this behavior is almost certainly not what you want. Have a look at how we save our preview images to see our recommended way of visualizing these arrays of normal values [here](https://github.com/apple/ml-hypersim/blob/21083ff46f3c51f22f5eb7fe29d9c093acf17899/code/python/tools/generate_hdf5_from_vrimg.py#L347). In our code, we call `imsave`, but you could just as easily call `imshow` instead.
