### ISSUE TITLE
Semantic Labeling

### ISSUE THREAD

**Issue by JonasFrey96** [apple/ml-hypersim#12]
Hello,

at first thanks for your work.
The labeling in the .hdf5 for the semantics is ambiguous. 

The NYU40 labels define 40 different classes in the range [0-39] and -1 for not labeled.
The provided .hdf5 files contain values from [-1,40] so did you define 41 objects? 

Best Jonas

**Comment by mikeroberts3000** [comment]
Hi! Great question.

A label value of -1 indicates not labeled, a label value of 0 [should never occur in our HDF5 images](https://github.com/apple/ml-hypersim/blob/21083ff46f3c51f22f5eb7fe29d9c093acf17899/code/python/tools/scene_generate_images_semantic_segmentation.py#L103), and a label value in the range 1-40 (inclusive) maps to the semantic classes defined [here](https://github.com/apple/ml-hypersim/blob/master/code/cpp/tools/scene_annotation_tool/semantic_label_descs.csv).

The NYU40 label set has an interesting history. The original NYUv2 dataset (Silberman et al. 2012) defines a label set consisting of 894 labels, and the NYU40 label set was defined later (Gupta et al. 2013). Gupta's [code](https://github.com/s-gupta/rgbd) expects the mapping from NYU894 labels to NYU40 labels to be stored in a `classMapping40` Matlab variable, but this variable isn't defined anywhere in his code. Fortunately, I have tracked down a [copy](https://github.com/ankurhanda/nyuv2-meta-data/blob/master/classMapping40.mat) of the original `classMapping40` variable, and it defines values in the range 1-40 (inclusive), not in the range 0-39 inclusive. This indexing convention makes sense, because the mapping was originally designed to be used in Matlab code. Anyway, as far as I can tell, the "official" representation of NYU40 labels is for them to be in the range 1-40 (inclusive), and this is the convention we adopt in Hypersim 🤓

**Comment by JonasFrey96** [comment]
Hello,

that was an awesome answer. 
I wish you best luck for your future research. 

Best Jonas
