### ISSUE TITLE
Generating images using a new trajectory

### ISSUE THREAD

**Issue by phongnhhn92** [apple/ml-hypersim#15]
Hi, Thanks for open-source the code, I think it is amazing.I have 2 questions:
1. I am interested in generating RGB and depths images from a custom trajectory (For example, I would like to move the camera around the room and the camera is gonna looking at the center of the room). May be you guys have done it somewhere in your code base but can you give me a hint how to do it ? 

2. After reading the README, I am wondering if camera_keyframe_orientations.hdf5 contains rotation matrix 3x3 in the cam-to-world format ?  Moreover, camera_keyframe_positions.hdf5 contains translation vector but it is in the asset coordinate. Does it mean I have to convert this translation vector to world coordinate to be on the same page with the above rotation matrix ?

**Comment by mikeroberts3000** [comment]
Hi! Asset coordinates _are_ the world coordinates, as defined by the artist at content creation time. We use the term asset coordinates to emphasize that we we haven't scaled the artist's units to be meters, and we haven't rotated the artist's coordinate system so that a particular axis points "up", etc.

The answers to your other questions are in the README,

- _"In [this tutorial example](https://github.com/apple/ml-hypersim/tree/master/examples/00_empty_scene), we use the Hypersim Low-Level Toolkit to add a camera trajectory...to a V-Ray scene"_.
- _"We store orientations as 3x3 rotation matrices that map points to world-space from object-space, assuming that points are stored as [x,y,z] column vectors."_

I hope that helps! 😄
