### ISSUE TITLE
2D 3D alignment

### ISSUE THREAD

**Issue by umyta** [apple/ml-hypersim#19]
Hi @mikeroberts3000, what would be a good way to check the 3D geometry's alignment with the generated 2D images? Is there any code that can demonstrate how to parse the scene information and align 3D geometry with the images using a different renderer such as blender or pytorch3d?

**Comment by mikeroberts3000** [comment]
Great question! It is always a good idea to experiment with the mesh data and camera data, to make sure you're interpreting it all correctly.

Let's assume you obtained your own copy of the source assets, exported an OBJ file for a particular scene, and then ran our `code/python/tools/generate_mesh_from_obj.py` code for that scene. In this case, you will have the following files in the `_detail/mesh` folder for that scene:

- `mesh_vertices.hdf5` contains a Vx3 array of vertex positions for the entire scene
- `mesh_faces_vi.hdf5` contains an Fx3 array of faces for the entire scene; this array stores integer IDs that refer to the values in the mesh_vertices array
  - If `mesh_faces_vi[i] == [a b c]`, it means that the _ith_ face in the scene is a triangle with vertices `(v0, v1, v2) == (mesh_vertices[a], mesh_vertices[b], mesh_vertices[c])`
- `mesh_faces_oi.hdf5` contains an Fx1 array with the "object ID" of each face; note that these "object IDs" are the most fine-grained segmentation available in our data, and are more fine-grained than our semantic instance IDs; in other words, each "semantic instance" in our data is composed of several "object IDs"
- `mesh_objects_sii.hdf5` contains a Bx1 array with the semantic instance ID of each object ID
- `mesh_objects_si.hdf5` contains a Bx1 array with the NYU40 semantic label for each object ID

To understand how to project this mesh data onto our pre-rendered images, here are some steps that will be helpful, in increasing order of difficulty:

- Load the mesh data into your own interactive viewer to make sure you understand the mesh format. For this step, don't worry about aligning the mesh data to any particular camera pose. I implement something like this in `code/python/tools/visualize_mesh.py` that you can use as a reference. In my code, I use mayavi for visualizing the mesh, but any interactive viewer library should work.

- Select a single semantic instance from the mesh data and visualize only that instance. Manually choose an instance that is visible in a pre-rendered image, get the semantic instance ID from the segmentation ground truth image, and use the semantic instance ID to select the appropriate vertices and faces from the mesh data. In my code (`code/python/tools/visualize_mesh.py`), I render each semantic instance separately in a different color, so there is already the necessary logic in this file to select a single semantic instance from the mesh data.

- Once you're familiar with the mesh format, try projecting the mesh vertices for a single instance onto one of our pre-rendered images. The projected vertices should align pixel-perfectly with the pre-rendered image. This step will require using the camera ground truth data for that particular image. I implement something like this in `code/python/tools/scene_generate_images_bounding_box.py` that you can use as a reference. In my code, I project each 3D corner of the semantic instance's bounding box (8 corners in total), but you could just as easily project mesh vertices instead of bounding box corners. In my code, there is a bit of extra logic to render lines rather than points, and to render everything in the correct depth order. You can ignore all of this additional logic, since the goal here is simply to project a collection of points in a way that aligns with a pre-rendered image (i.e., you don't need to worry about rendering lines, and you don't need to worry about rendering things in the correct depth order). At this point, you have re-implemented the complete geometric transformation pipeline in Hypersim.

Give these steps a try, and post here if you run into any problems 😄
