### ISSUE TITLE
The rendered images color space order and unbalanced value distribution

### ISSUE THREAD

**Issue by peiyaoooo** [apple/ml-hypersim#20]
Hi Roberts,
     Thank you for your impressive work on the photorealistic synthetic dataset Hypersim.
      There are some points about the dataset fusing me. Would you be willing to help me with these?
### [color space order]     
The RGB space of these hdf5 or jpg file follows RGB or BGR order. These overall tones of  preview images (such as ai_001_001,ai_001_003) are too blue. ( Maybe it is only my feeling.) I checked some codes for this problem ( Line 266 in [https://github.com/apple/ml-hypersim/blob/master/code/python/tools/generate_hdf5_from_vrimg.py]; Line 88 in  [https://github.com/apple/ml-hypersim/blob/master/code/python/tools/scene_generate_images_tonemap.py] ). It seems that the saved array follow the RGB order while the tone of the visual result is blue . Is the original source in blue tone? When I flipped the channel order, I got a more realistic photo.

![flip_comparison](https://user-images.githubusercontent.com/25130340/116339796-a8cecb80-a810-11eb-87a2-8be088312a8c.png)

 ### [unbalanced value distribution]   
The value ranges of different viewpoints based on the same scene are different. For example, the value of  'ai_002_001\\images\\scene_cam_00_final_hdf5\\frame.0075.color.hdf5' ranges from - to 2.20899 while the maximum of ''ai_002_001\\images\\scene_cam_00_final_hdf5\\frame.0071.color.hdf5'(@768X1024)  is 15.484 and only 41 pixel values are larger than 2.4242. Are these high values are outliers? These few pixel values are seriously bad  to HDR data normalizatoin. 

![distribution_comparison](https://user-images.githubusercontent.com/25130340/116342396-24327c00-a815-11eb-8611-6e0c8b14f315.png)

Thank you for your attention and hope for your reply.

**Comment by mikeroberts3000** [comment]
Hi! Great questions.

First, the scene you showed in your figure (ai_001_003) really is that shade of blue. You can see it in the thumbnails on the original artist's website:

https://evermotion.org/shop/show_product/archinteriors-vol-1/37

These artist thumbnails are not rendered by our pipeline, and therefore offer an independent sanity check for what our rendered images should look like. We do not expect our rendered images to match these artist thumbnails _exactly_, because the artist renderings use a different tone-mapping algorithm, and sometimes also have manual post-processing applied to them. In contrast, we intentionally avoid manual post-processing in our pipeline, and we use a simple tone-mapping algorithm to maximize the consistency of our output. Despite these minor differences, the artist thumbnails should be visually similar to our rendered images (i.e., you'd be able to tell by visual inspection if we accidentally swapped color channels).

Second, our HDF5 data is the most raw possible data available from the renderer. It has no normalization or tone mapping or gamma correction or other non-linear color transformations applied to it. In other words, the value at each pixel is proportional to outbound radiance. There is a huge range of radiance values in a typical real-world indoor scene, and therefore we expect a huge range of radiance values in our HDF5 data. It is also expected that different parts of the _same scene_ have different ranges of radiance values. For example, a really bright light might be visible in one part of the scene, but not another, and this could lead to one image having a wider range of radiance values than another.

I agree that working with raw rendered data comes with additional challenges. But it also has distinct advantages. In particular, our data adheres to the equation `final_image == diffuse_reflectance * diffuse_illumination + non_diffuse_residual`, which is a useful property in inverse rendering applications, and this property would not hold if we applied non-linear color transformations to our rendered data. Therefore, we leave it up to the user to apply whatever tone-mapping operations (if any) that makes the most sense in their application. If you don't like the wide range of radiance values in our HDF5 data, can you just apply our tone-mapping code in your application?

**Comment by rikba** [comment]
How did you normalize your images in the end @peiyaoooo?

In our project, we want to find matches across images of the same scene. Thus consistent pixel intensities should help.

I think frame based MIN/MAX normalization is not the correct way to go, because applied to different frames from the same scene, the images and probably also intensity gradients are quite different. 
```img_normalized = cv2.normalize(np.float32(img_orig), img_normalized, 0, 1, cv2.NORM_MINMAX)```

ai_001_001, cam00, frame 0
![min_max](https://user-images.githubusercontent.com/11293852/117465572-1fc33d00-af52-11eb-86fc-6c136e4a32b4.png)

ai_001_001, cam00, frame 1
![min_max_2](https://user-images.githubusercontent.com/11293852/117466816-682f2a80-af53-11eb-8f09-1695d2155545.png)

**Comment by mikeroberts3000** [comment]
@rikba The dynamic range in raw Hypersim images is huge, just like dynamic range of real images from a real camera. It is not useful to map the min and max values in each image linearly to the range [0,1], which is what `cv2.normalize(...)` is doing. Instead, you need to apply a tone-mapping algorithm to compress the huge dynamic range in these images in a meaningful way.
