### ISSUE TITLE
Fov camera parameters used for rendering

### ISSUE THREAD

**Issue by cartacamilla** [apple/ml-hypersim#23]
Hi,

I've seen that in the file modify_vrscene_add_camera.py you introduce a hack to bypass the rounding error when writing to vrscene files.
Can you go in more details as to why this is needed? You say that this enables more accurate results as the uv values match the fov stored in the vrscene file, but aren't you determining the fov of the vrscene? Could you confirm that the camera fov used for all the renderings are fov_x = 0.7871435 and fov_y = 0.6038145121402665?

Also, would it be possible in your opinion to reproduce the results you have (or at least similar) with a larger fov?

Thank you for your time.

**Comment by mikeroberts3000** [comment]
Hi! Great questions.

Where are you getting those values for `fov_x` and `fov_y`? For all of our rendered images, we set `fov_x == np.pi / 3.0 == 1.0471975511965976`. We set the FOV [here](https://github.com/apple/ml-hypersim/blob/master/evermotion_dataset/_vray_user_params.py#L15) or [here](https://github.com/apple/ml-hypersim/blob/master/evermotion_dataset/_vray_user_params.py#L78), depending on the type of camera that is present in the scene.

It is definitely possible to re-render the Hypersim images with whatever FOV you prefer. We don't have plans to render our dataset again with a different FOV, but you could by making the appropriate changes to `_vray_user_params.py` and re-running our code.

The chunk of code you're referring to is an implementation detail that most users don't need to worry about, and is only executed in very specific settings. Indeed, it did not get executed at all when we rendered the Hypersim images that we publicly released. I'll explain the purpose of this code in a separate post, but the main point is that it had no impact on the FOV of the rendered images that we publicly released.

**Comment by mikeroberts3000** [comment]
So why do we need that (admittedly confusing) chunk of code that you referred to in your original question?

The need for this code arises because we want to support rendering with very general lens distortion effects. More specifically, we want users to be able to specify the exact ray they want to cast at every pixel, because then we can render data for all kinds of custom cameras. Do you have a custom camera with really weird fisheye lens distortion? No problem. Just provide `modify_vrscene_add_camera.py` with a dense array of rays in camera space that match your camera model, and we'll make sure that our final rendered images match your camera model. We think that requiring users to specify a dense array of rays in camera space is the cleanest way to specify lens distortion effects. Otherwise we'd need to decide in advance on some kind of compact parameterization (e.g., the polynomial distortion model used in OpenCV), and that parameterization might not be a good fit for your specific camera.

Under the hood, V-Ray supports user-specified per-pixel lens distortion effects, but it does so in a somewhat indirect way. Instead of specifying a dense array of rays in camera space, V-Ray requires you to specify an FOV and a dense array of UV-values, where each UV-coordinate is in the range [-1,1], and each UV-value corresponds to a point on the undistorted 2D image plane (see the [V-Ray documentation](https://docs.chaosgroup.com/display/VMAX/VRayPhysicalCamera#VRayPhysicalCamera-Distortion) for details). Note that the FOV is required to map a particular UV-value to a particular ray in camera space.

There is a mismatch between the interface we want to provide to our users (specifying a dense array of rays in camera space), and the interface that our renderer supports (specifying an FOV and a dense array of UV-values). Fortunately, it is easy to convert back and forth from one representation to the other. When you provide us with an array of camera rays, we simply find the smallest undistorted camera frustum that will accomodate all of your rays (in other words, we solve for the smallest possible FOV), and then express your rays in terms of UV-values that are correct for that camera frustum.

When expressing your rays in terms of UV-values, there is no harm in choosing a camera frustum that is slightly larger than necessary, and we do this intentionally to avoid rounding errors. For example, suppose we determine that the smallest possible FOV that will accomodate all of your rays is `fov_x = 1.23456789`, and we compute UV-values that are correct for this exact FOV. As our pipeline loads, transforms, and saves various intermediate copies of the scene, the V-Ray Python SDK may only save our original value of `fov_x = 1.23456789` as `fov_x = 1.23`. In this case, the UV-values that we computed previously will be slightly incorrect. To avoid this problem, we apply some of our own numerical padding when we're solving for the appropriate FOV (e.g., we will intentionally set `fov_x = 1.24`), so that it can be loaded and saved without any loss of precision by the V-Ray Python SDK, and our UV-values will be exactly correct.

We have determined empirically (using our own bare-bones ray tracer that we implemented from scratch as ground truth), that this approach leads to V-Ray renderings that more faithfully match your user-specified lens distortion. In other words, if you don't apply this numerical padding carefully, then you'll think that you're rendering with a particular lens distortion model, but V-Ray will actually be rendering with a slightly different lens distortion model.
