### ISSUE TITLE
Camera-space surface normals

### ISSUE THREAD

**Issue by Ainaz99** [apple/ml-hypersim#26]
Hi,

I recently came across some issue in the camera-space surface normals (`normal_cam`). Looks like there are some normals that are pointing the same way as the camera, instead of against it. Does this make sense? 
Here are some examples:
![frame 0001 normal_cam](https://user-images.githubusercontent.com/69212889/119260012-20143700-bbe6-11eb-9c27-d47c17158e4b.png)
![frame 0017 normal_cam](https://user-images.githubusercontent.com/69212889/119260056-49cd5e00-bbe6-11eb-9c31-1c3f1979a78f.png)
![frame 0077 normal_cam](https://user-images.githubusercontent.com/69212889/119260082-71242b00-bbe6-11eb-9a1c-f46af318d811.png)

Thanks!

**Comment by mikeroberts3000** [comment]
Hi! Great question.

We have encountered several issues with the normals in our data also. The normals in our data are defined by the artist, and artists don't always define them correctly. To be fair on the artists, there is no way to define outward-facing normals on a triangle mesh in a completely unambiguous way, because the concept of an "inward-facing" vs "outward-facing" normal is ill-defined for triangle meshes.

Anyway, we have encountered the following occasional issues with surface normals in our data: (1) the surface normal might be zero; (2) the surface normal might not have unit length; and (3) the surface normal might point "inward", which is the specific issue you're alluding to in your question.

You will need to deal with this issue specifically when you load our data. See [here](https://github.com/apple/ml-hypersim/blob/master/code/python/analysis/dataset_generate_image_statistics.py#L576) for a code snippet that re-orients all the normals in an image to face towards the camera.

**Comment by ZachL1** [comment]
May I ask if this has been fixed? Does this problem still exist in the normal in the downloaded data set?

**Comment by mikeroberts3000** [comment]
We have not addressed this issue in the data, i.e., it is expected that you handle it in your data loader.

**Comment by ZachL1** [comment]
I see, thanks for your quick reply.
