### ISSUE TITLE
Reverse mapping the depth from the preview images

### ISSUE THREAD

**Issue by liuzhy71** [apple/ml-hypersim#33]
Great work on building such a good dataset. But it is unfortunate that I do not have enough storage for hdf5 files. So I downloaded the preview file. 

And in these files, the depth and render_entity_id is mapped to a rgb image. How can I map those RGB value back to the depth value and entity ID?

**Comment by mikeroberts3000** [comment]
Great questions.

First, are you sure you want the `render_entity_id` image? This image contains the most fine-grained segmentation possible, where each segment is a low-level object part that is not necessarily semantically meaningful. This segmentation is more fine-grained than our `semantic` and `semantic_instance` images.

Second, mapping the RGB preview images back into scalar data is not recommended. In our `render_entity_id` preview images, there are more ID values than there are unique colors in the color map, so it is not guaranteed that each ID maps to a unique color. In our `depth_meters` preview images, the color values are not consistently normalized, so you would need additional information (i.e., the min and max depth values in each image) in order to recover the correct depth from the color image. Why go to all of this extra trouble, when you can just work with the HDF5 data directly and get the exact information you need?

If storage space is an issue, I recommend modifying [Thomas Germer's](https://github.com/99991) [selective download script](contrib/99991) to download an HDF5 file, load it, save it in whatever compressed format you prefer, and then discard the original HDF5 file. Note that we [already](https://github.com/apple/ml-hypersim/blob/master/code/python/tools/generate_hdf5_from_vrimg.py#L322) save our HDF5 files as int16 and float16 with maximum gzip compression, so it's not clear how much further you'll be able to compress them without losing important information.

**Comment by liuzhy71** [comment]
Thank you very much. I did not realize the mapping problem when posting the issue. Now I will use the render entity image.
