### ISSUE TITLE
Semantic Labels

### ISSUE THREAD

**Issue by Frank-Mic** [apple/ml-hypersim#34]
Hey Mike,

I saw the other resolved issue about semantic labels (https://github.com/apple/ml-hypersim/issues/12) where you explain that HyperSim follows the NYU-40 labeling schema (IDs: -1, 1-40) and you are linking to the label table here: https://github.com/apple/ml-hypersim/blob/master/code/cpp/tools/scene_annotation_tool/semantic_label_descs.csv

I am trying to use the semantic label in my project as well but I came across a label in one of the hdf5 files that is not in accordance to your statement in the above mentioned link. I am looking at image sequence ai_002_001 image 51. Checking location [x=280, y=750] in the hdf5 file ai_002_001/images/scene_cam_00_geometry/frame.0000.render_entity_id.hdf5 shows the ID 120. Could you help me figure out if I am doing something wrong or if this is expected.

**Comment by mikeroberts3000** [comment]
Hi. Great question. Thank you for being so specific! Our `render_entity_id` images contain fine-grained segmentation information. This segmentation information is not semantically meaningful. Look at our `semantic` and `semantic_instance` images instead.

The reason we generate the fine-grained `render_entity_id` images during rendering is as follows. When we render our images, we haven't necessarily semantically labeled the scene yet. So we render our fine-grained `render_entity_id` images, and convert these into `semantic` and `semantic_instance` images in a post-process using the labeling information we obtain from our custom labeling tool. This pipeline design enables us to render images and label scenes in parallel, and enables us to re-label our scenes (e.g., with a different set of labels) without needing to re-render images.

**Comment by Frank-Mic** [comment]
Thank you for your detailed answer.
I realized that was using the wrong data *render_entity* instead of *semantic*. I've got everything working now.

I have a semi related question. Can I assume that the data (semantic label, 3D world point) at a location in the image is always representing the object closest to the camera. If I am, for example, looking through a window seeing the floor of a patio, I would get the window label as well as the 3D world position on the glass surface instead of the label floor and the 3D world point on the patio floor?

**Comment by mikeroberts3000** [comment]
In the case you describe, the semantic label would be `window`, not whatever object is visible on the other side of the window. Likewise if you're looking at a mirror. The semantic label would be `mirror`, not the object that is visible through the mirror's reflection.

I would argue that this is the correct convention. But regardless of what you think of this convention, it's the convention we're stuck with because of how V-Ray is implemented. V-Ray returns the ID of the nearest surface, even if this surface is transparent or reflective. I believe V-Ray can be configured to return multiple IDs per pixel, but I have not experimented with this functionality.

That being said, in the Hypersim data specifically, many of the scenes are missing windows. In these scenes, the artist might have created a realistic-looking window frame, but did not add an actual window, i.e., a flat surface made out of transparent glass. (I would have preferred for all scenes to have transparent glass windows, because then it would be easier to design camera trajectories that don't accidentally drift outside the intended viewing region of the scene.) Anyway, in these cases, you will see the label of whatever object is on the other side of the window.

**Comment by Frank-Mic** [comment]
It makes sense that the nearest surface is use to determine the IDs. It would be nice to be able to have multiple outputs for those kind of surfaces but I agree that this comes with a large effort.

Thanks again Mike.
