### ISSUE TITLE
Image alignment problem

### ISSUE THREAD

**Issue by liuzhy71** [apple/ml-hypersim#39]
Hello,

Following the previous problem, I managed to generate the edges of the objects in the scene with the assets files. However, when inspecting the alignment of the edges, I find that my edges from the mesh files are slightly tilted away from the rendered images. So I also tested generate a plain image from the provided `scene_annotatiaon_tool`. 

For example, for scene `ai_026_011`, `cam_00`, image id `0099`, the rendered image is
![frame 0099 tonemap](https://user-images.githubusercontent.com/16524611/137329642-28c69030-0596-40ed-9091-156ae7349dd7.jpg)

My own image is
![frame 0099 mesh_edge](https://user-images.githubusercontent.com/16524611/137329795-5c925c31-3d7b-4599-85a4-cc6403d53b27.png)

And the image from the `scene_annotation_tool` is 
![screenshot](https://user-images.githubusercontent.com/16524611/137329949-390e1247-d745-41bc-a614-9a0ef7741d92.png)

Is there any updates on camera position/orientations or different FoVs and far/near clipping plane values since August?

How can I align my images with the rendered images. I think maybe others will encounter this problem as well. So I need some guidance on this one.

**Comment by liuzhy71** [comment]
> Hi! Thanks for your question. I think you are encountering the same issue as described in #24 and #25. This issue is still unresolved, but we're making progress. Please see the discussion in those threads for updates.
> 
> How are you generating your wireframe image? Did you modify our scene annotation tool somehow? Or did you generate it with your own renderer.

I wrote a simple render for the second image.

**Comment by mikeroberts3000** [comment]
Hi @liuzhy71, I have some good news. I just checked in some data and example code that addresses this issue.

In the [`contrib/mikeroberts3000`](https://github.com/apple/ml-hypersim/tree/master/contrib/mikeroberts3000) directory, I provide a modified perspective projection matrix for each scene that can be used as a drop-in replacement for the usual OpenGL perspective projection matrix, as well as example code for projecting world-space points into Hypersim images.

I apologize that it took so long to address this issue. It was especially challenging to debug because V-Ray's behavior wasn't well-documented, and I've been busy with other projects and holiday travel.
