### ISSUE TITLE
Computing camera trajectories

### ISSUE THREAD

**Issue by cartacamilla** [apple/ml-hypersim#42]
Hi,
I have a question concerning reproducing the camera trajectories computation.
I'm trying to already reproduce the code as-is before adding any modification (the final objective is to have continuous trajectories similarly to a video).

To re-compute the trajectories, these are the steps I run:
```bash
 python toolkit/code/python/tools/scene_generate_camera_trajectories_asset_export.py --scene_dir /path/to/scene

 python toolkit/code/python/tools/generate_mesh_from_obj.py --in /path/to/scene/_asset_export/scene.obj --out /path/to/scene/_detail/mesh/

 python toolkit/code/python/tools/scene_generate_octomap.py --scene_dir /path/to/scene 

python toolkit/code/python/tools/scene_generate_camera_trajectories_random_walk.py --scene_dir /path/to/scene
```
When I run the last step, this is the output I obtain:
```bash
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK] Begin...
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK] Input camera cam_Camera02, output camera cam_00...

/home/ccarta/Workspace/Arcadia/DataCapture/Hypersim/ml-hypersim/toolkit/code/cpp/bin/generate_camera_trajectory_random_walk 
--mesh_vertices_file=../hypersim-data/scenes/ai_001_001/_tmp/_tmp_mesh_vertices.hdf5 --mesh_faces_vi_file=../hypersim- 
data/scenes/ai_001_001/_tmp/_tmp_mesh_faces_vi.hdf5 --start_camera_position_file=../hypersim-data/scenes/ai_001_001 
/_tmp/_tmp_start_camera_position.hdf5 --start_camera_orientation_file=../hypersim-data/scenes/ai_001_001 
/_tmp/_tmp_start_camera_orientation.hdf5 --camera_rays_file=../hypersim-data/scenes/ai_001_001/_tmp/_tmp_camera_rays.hdf5 
--camera_rays_distances_to_center_file=../hypersim-data/scenes/ai_001_001/_tmp/_tmp_camera_rays_distances_to_center.hdf5 
--octomap_file=../hypersim-data/scenes/ai_001_001/_detail/octomap/octomap.bt --octomap_free_space_min_file=../hypersim- 
data/scenes/ai_001_001/_tmp/_tmp_octomap_free_space_min.hdf5 --octomap_free_space_max_file=../hypersim-data/scenes 
/ai_001_001/_tmp/_tmp_octomap_free_space_max.hdf5 --n_samples_random_walk=100 --n_samples_octomap_query=1000 
--n_samples_camera_pose_candidates=20 --n_voxel_size=3.9370079215952636 
--n_query_half_extent_relative_to_start_file=../hypersim-data/scenes/ai_001_001
/_tmp/_tmp_n_query_half_extent_relative_to_start.hdf5 --n_query_half_extent_relative_to_current_file=../hypersim-data/scenes
/ai_001_001/_tmp/_tmp_n_query_half_extent_relative_to_current.hdf5 --output_camera_look_from_positions_file=../hypersim-
data/scenes/ai_001_001/_tmp/_tmp_output_camera_look_from_positions.hdf5 --output_camera_look_at_positions_file=../hypersim-
data/scenes/ai_001_001/_tmp/_tmp_output_camera_look_at_positions.hdf5 --output_camera_orientations_file=../hypersim-
data/scenes/ai_001_001/_tmp/_tmp_output_camera_orientations.hdf5 --output_intersection_distances_file=../hypersim-data/scenes
/ai_001_001/_tmp/_tmp_output_intersection_distances.hdf5 --output_prim_ids_file=../hypersim-data/scenes/ai_001_001
/_tmp/_tmp_output_prim_ids.hdf5

[HYPERSIM: GENERATE_CAMERA_TRAJECTORY_RANDOM_WALK] Begin...
Reading binary octree type OcTree
[HYPERSIM: GENERATE_CAMERA_TRAJECTORY_RANDOM_WALK] Constructing Embree data...
[HYPERSIM: GENERATE_CAMERA_TRAJECTORY_RANDOM_WALK]
[HYPERSIM: GENERATE_CAMERA_TRAJECTORY_RANDOM_WALK]
[HYPERSIM: GENERATE_CAMERA_TRAJECTORY_RANDOM_WALK]
[HYPERSIM: GENERATE_CAMERA_TRAJECTORY_RANDOM_WALK] WARNING: CAMERA DOESNT OBSERVE ANY PART OF THE SCENE. ALL INTERSECTION DISTANCES ARE AT INFINITY. GIVING UP.
[HYPERSIM: GENERATE_CAMERA_TRAJECTORY_RANDOM_WALK]
[HYPERSIM: GENERATE_CAMERA_TRAJECTORY_RANDOM_WALK]
[HYPERSIM: GENERATE_CAMERA_TRAJECTORY_RANDOM_WALK]
[HYPERSIM: GENERATE_CAMERA_TRAJECTORY_RANDOM_WALK] WARNING: generate_camera_trajectory_random_walk DID NOT EXECUTE SUCCESSFULLY. GIVING UP.
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK] WARNING: random_walk_utils.generate_camera_trajectory_random_walk DID NOT EXECUTE SUCCESSFULLY. SKIPPING.
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK] Finished.
```

I'm not sure where to start debugging, so I would gladly accept any pointers in the right direction.

Also, the visualization tools for the octomap and the camera trajectory work and seem to give plausible results.

**Comment by mikeroberts3000** [comment]
Hi Camilla, thanks for this detailed question. The sequence of steps looks good to me.

Here is some quick background on the issue. In our algorithm that generates camera trajectories, we represent trajectories internally as sequences of "look-from" positions and "look-at" positions. In order to initialize our algorithm, we use an artist-defined camera position as the initial "look-from" position, and we define the initial "look-at" position by raycasting from the artist-defined camera pose.

If the artist-defined camera pose doesn't observe any scene geometry, then we can't define a sensible look-at position, and we give up. This case is rare, but it can happen when an artist accidentally leaves a spurious camera in the original 3ds Max scene that is outside the intended viewing region for the scene.

You're encountering this case for the `ai_001_001` scene, which is weird, because this scene should have exactly one artist-defined camera pose, and that camera pose should observe valid scene geometry at every pixel. It is unclear to me why you are encountering this issue for this scene.

Here are some things to try, roughly sorted by amount of effort required.

1. Is the mesh data that you exported from 3ds Max valid? When you run our `visualize_mesh.py` tool, do you see a valid triangle mesh?
2. Is the artist-defined camera pose that is exported from 3ds Max valid? Our `scene_generate_camera_trajectories_asset_export.py` tool, which you have already executed, converts the raw artist-defined camera pose exported from 3ds Max into a standard Hypersim camera trajectory with exactly one camera pose. This means that you can use our `visualize_camera_trajectory.py` tool to visually inspect the artist-defined camera-pose. When using this tool, just set the `--camera_trajectory_dir` argument to `path/to/scene/_asset_export/cam_Camera02`. Is the camera pose at a sensible location within the scene?
3. What happens when you set `--camera_trajectory_dir` to our publicly released camera trajectory for this scene? Is our publicly released camera trajectory overlaid on the scene in a sensible way? If not, can you hack our `visualize_camera_trajectory.py` tool to permute and/or scale the mesh coordinates to make the camera trajectory match the mesh? It's possible that you exported the mesh in a way that permutes or scales the mesh coordinates without realizing it, especially because we don't provide code for this step in this repository.
4. When you run our `scene_generate_camera_trajectories_random_walk.py` tool, you can pass in a `--use_python_reference_implementation` flag to use a Python implementation, rather than the default C++ implementation. These two implementations are intended to be identical, but they don't produce exactly the same results because they use different random number generators. Regardless, the Python implementation should catch the case you're encountering (see [here](https://github.com/apple/ml-hypersim/blob/master/code/python/tools/scene_generate_camera_trajectories_random_walk.py#L337)), and is probably easier to debug than the C++ implementation.

Please do post your findings here.

**Comment by cartacamilla** [comment]
Thank you for the many pointers you gave me.
I will list here the answers to every point above:

1. Here is the output for ai_001_001, to me it looks correct
![image](https://user-images.githubusercontent.com/32430116/141277459-20360b04-e945-443b-a87b-eacbda8d1ba5.png)
2. Here's the visualization of the artist camera in the scene, which also seems correct
![image](https://user-images.githubusercontent.com/32430116/142427788-d5846f0d-3ad9-4624-8cbe-4397a0836d0b.png)
3. The cam00 looks reasonable to me. I also checked with 3dsMax and the transforms are the same
![image](https://user-images.githubusercontent.com/32430116/142431349-334e610c-5042-4156-b105-14ef3677de39.png)
4. When I tried running the python implementation, the error was similar to the previous:
```bash
$ python toolkit/code/python/tools/scene_generate_camera_trajectories_random_walk.py --scene_dir ../hypersim-data/scenes/ai_001_001 --use_python

[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK] Begin...
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK] Input camera cam_Camera02, output camera cam_00...
Reading binary octree type OcTree
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK]
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK]
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK]
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK] WARNING: CAMERA DOESNT OBSERVE ANY PART OF THE SCENE. ALL INTERSECTION DISTANCES ARE AT INFINITY. GIVING UP.
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK]
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK]
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK]
[HYPERSIM: SCENE_GENERATE_CAMERA_TRAJECTORIES_RANDOM_WALK] Finished.

``` 
I checked during computation and it seems that embree fails to compute the intersection_distances [here](https://github.com/apple/ml-hypersim/blob/master/code/python/tools/scene_generate_camera_trajectories_random_walk.py#L251)

I tried running the command generate_ray_intersection without the --silent and while I do not have an error message, the computed ray float and int are all inf.

**Comment by mikeroberts3000** [comment]
That's weird. Everything looks good to me so far.

Can you debug one level deeper? Can you add some extra print statements to the `generate_ray_intersections` tool (it's just 200 lines of C++ code) to figure out what's going on? Is [this](https://github.com/apple/ml-hypersim/blob/master/code/cpp/tools/generate_ray_intersections/main.cpp#L184) code being executed? When calling `generate_ray_intersection`, all the inputs (mesh, rays, etc) are saved to a temp folder. So you can inspect all the HDF5 files using the `h5dump` tool that ships with the HDF5 library or h5py. Are they what you expect?

**Comment by cartacamilla** [comment]
Interestingly, today I tried the same code on another machine and it worked perfectly...
I will do some tests to understand the difference.

**Comment by mikeroberts3000** [comment]
Ah, that's good news. But it's also somewhat creepy. This latest development makes me think even more that it's an issue with Embree on the non-working machine. If it was an issue with our code, or your 3ds Max exporting code, we would expect both machines to be affected. Maybe the non-working version of Embree requires an extra initialization step or something that we're not doing in our code.
