### ISSUE TITLE
Questions aboud RGB image and depth

### ISSUE THREAD

**Issue by Tord-Zhang** [apple/ml-hypersim#45]
Hi, thanks for your wonderful work !

I got two questions about how to use this dataset. 
1. When using this dataset for downstream tasks like segmentation or depth estimation, which RGB image data should I use? The data in .color.hdf5 seems to have some pixels that have invalid values.
2. The _depth_meters.hdf5 contains distance to optical center of camera instead of depth. So how can I transform it into depth?
Thanks !

**Comment by mikeroberts3000** [comment]
Hi!

- If you just want to get something quick and dirty working, use our `tonemap.jpg` preview images.
- If you want to do things the right way, use the `color.hdf5` images and apply your own tone-mapping operator, e.g., as a custom transform in your data loader. We provide simple tone-mapping code. See the README for details.
- See the README for a code snippet that converts our `depth_meters.hdf5` images into planar depth images.

What are the invalid `color.hdf5` values that you're seeing? Here are some things to keep in mind.
  - The `color.hdf5` images contain unnormalized radiance values, and are therefore not guaranteed to be in the range [0,1]. This is why you need to apply a tone-mapping operator.
  - Occasionally, there are empty pixels in our data, i..e, pixels that do not contain any scene geometry. These pixels are filled with a default background color, so they shouldn't be set to `nan` or `inf`.
  - Very occasionally, there are negative values in the `color.hdf5` images, because it is possible for the original scene assets to contain negative lights.

**Comment by Tord-Zhang** [comment]
@mikeroberts3000 Thanks for your quick detailed answers! So what's the difference between directly using tonemap.jpg and generate tonemap image with the script in code/python/tools ?

**Comment by mikeroberts3000** [comment]
Great question. If you use all of our default tone-mapping parameters, there is no difference between using tonemap.jpg and generating your own tone-mapped images in the data loader. But if you do your own tone-mapping, then you can randomize the tone-mapping parameters, and squeeze more meaningful signal out of the data. This is roughly equivalent to augmenting your dataset with multiple different camera exposure settings for each image.
