### ISSUE TITLE
Can this dataset generate 2d floorplan images? 2d layout images?

### ISSUE THREAD

**Issue by universewill** [apple/ml-hypersim#47]
Can this dataset generate 2d floorplan images? 2d layout images? How to do it?

**Comment by mikeroberts3000** [comment]
I'm sorry but I don't understand the question. Can you describe what you want to do in a bit more detail?

**Comment by universewill** [comment]
> I'm sorry but I don't understand the question. Can you describe what you want to do in a bit more detail?

By 2d floorplan i mean something like this:
![1](https://user-images.githubusercontent.com/6790730/193185342-c0fea061-4baa-40d4-8c55-931a71889a50.png)

I want to get the 2d bboxes of the walls, windows and the furnitures from a top-down view. Can this data be generated by this dataset?

**Comment by mikeroberts3000** [comment]
Hi, thank you for clarifying. I think what you want to do is possible but not easy. I'll comment on the relative difficulty of each piece below.

- Obtaining the 2D bounding boxes of windows and furniture is easy. You can download semantically labeled 3D bounding boxes directly from this GitHub repo. It is easy to convert 3D bounding boxes to 2D bounding boxes.
- Rendering a top-down orthographic view of each scene with semantic labels is easy, but you'll need to pay to obtain the triangle mesh for each scene (link in the README).
- Obtaining 2D bounding boxes for walls is difficult. To reason about walls, you'll need to obtain the triangle mesh for each scene, and use our semantic labels to extract the parts of each mesh that are labeled as walls. Our walls are not labeled at the instance level, so you'll get a big triangle soup for all of the walls in a scene. From here, you'll need to project this triangle soup into a suitable floor plan representation. This projection step is itself is a somewhat ill-posed problem, because many of our walls are slanted. What is the correct way to project slanted walls onto your floor plan?

I'll also comment on something in your example image that you don't mention in your text.

- Hypersim meshes do not include semantic labels at the room level (e.g., living room, kitchen, etc). You'll get a big triangle soup for all of the floors in each scene.
- Doors are labeled at the instance level, but we have not annotated the direction that they open.
