### ISSUE TITLE
how to align labels with bounding boxes

### ISSUE THREAD

**Issue by SyanneL** [apple/ml-hypersim#49]
Hi, I have a question regarding aligning each label with its corresponding bounding boxes per scene. I found objects information under metadata_objects.csv, but I am wondering how I could align each of them with bounding boxes generated by scene_generate_images_bounding_box.py. Thanks!

**Comment by mikeroberts3000** [comment]
Hi! In order to address this question, we need to understand exactly how labeling works in Hypersim.

Each scene has _O_ _low-level objects_. Each low-level object has a _name_ (stored in `metadata_objects.csv`), a _semantic ID_ (stored in `mesh_objects_si.hdf5`), and a _semantic instance ID_ (stored in `mesh_objects_sii.hdf5`). Each of these files has exactly _O_ entries, because there is one entry per low-level object.

Each _semantic ID_ is in the range [-1, 40], and corresponds to an NYU40 label. A semantic ID of -1 means unlabeled, and a semantic ID of 0 never occurs in our data. Multiple low-level objects can have the same semantic ID.

Each _semantic instance ID_ is in the range [-1, _S_]. A semantic instance ID of -1 means unlabeled, and a semantic instance ID of 0 never occurs in our data. Multiple low-level objects can have the same semantic instance ID. Each semantic instance ID has a bounding box (stored in `metadata_semantic_instance_bounding_box_*.hdf5`). Each of these bounding box files has exactly _S_+1 entries, because there is one entry per semantic instance. The 0th entry in each of these files is set to inf, since a semantic instance ID of 0 never occurs in our data.

This data schema implies that we must use a bit of fancy indexing to obtain a semantic label for each bounding box. Essentially, we must find the semantic label corresponding to each semantic instance ID. We can use the following strategy.

1. For each semantic instance ID, we find all the low-level objects with that semantic instance ID. Now we have a set of low-level object IDs.
2. We look up the semantic label for each low-level object ID we found in step 1. Now we have a set of semantic labels.

Most of the time, all of the semantic labels for a particular semantic instance ID will be identical, but this is not guaranteed by our data schema. In the rare case that you obtain multiple semantic labels, you can just take a majority vote, or if you're being really strict, you could assume that such a bounding box doesn't have a label.

**Comment by mikeroberts3000** [comment]
Yes! We store a mapping from semantic IDs to string labels here:https://github.com/apple/ml-hypersim/blob/main/code/cpp/tools/scene_annotation_tool/semantic_label_descs.csv
