### ISSUE TITLE
Scene detailed information

### ISSUE THREAD

**Issue by Stefanpe95** [apple/ml-hypersim#51]
Greetings,

I have a question. I've tried to find some detailed metadata about each scene, only I've found are python scripts in code/python/analysis, but they do not provide such information. I'm not interested in the scene number as information, but I'm more interested in the name or what is that scene/room (museum, library, kitchen...). Could you provide some help?

Thank you.

**Comment by mikeroberts3000** [comment]
Hi @Stefanpe95, great question. We provide our "scene type" labels at the granularity of individual camera trajectories rather than scenes. This is because a scene in Hypersim can be an entire apartment with multiple rooms (e.g., kitchen, living room, etc). It is not clear how to apply a single label to such a scene. In contrast, each of our camera trajectories tends to stay in a single room, so it is easier to apply a single label to each camera trajectory.

It is worth noting that even labeling at the granularity of camera trajectories is an imperfect strategy, because a single camera trajectory can sometimes drift from one room to another. But it is much less ambiguous than trying to label entire scenes.

Regardless, we provide this data at `evermotion_dataset/analysis/metadata_camera_trajectories.csv` in this GitHub repository.
