### ISSUE TITLE
Camera height wrt the floor

### ISSUE THREAD

**Issue by dcaffo98** [apple/ml-hypersim#56]
Hi, thank you for releasing your dataset.
I'm trying to design a model capable of predicting the **_camera height from the floor_** (i.e. the floor is at `height=0.0 m`), taking as input nothing but a single RGB image. I thought I could use the z coordinate of the `camera_keyframe_positions.hdf5` assets to set up a regression framework, after converting the asset units into meters. I realized that there are some negative values, meaning that the world coordinate system (_asset coordinate system_) is not set so to have the floor level at 0.0 meters. Can you confirm this?
Additionally, with the data currently provided, is there any way to know the offset of the floor level for each scene? With that, I could easily translate all the height values to have the origin of the z-axis at the floor level.
Thank you

**Comment by mikeroberts3000** [comment]
Hi! Great question.

It makes sense to me that there might be negative values for the camera z-coordinates in `camera_keyframe_positions.hdf5`, because there is nothing to guarantee that the floor of a scene is set to any particular z-value. The world coordinate system used throughout our metadata (e.g., in `camera_keyframe_positions.hdf5` and elsewhere) is artist-defined, and we don't attempt to make any modifications to it. And even if we did attempt to modify it, it would not be possible to unambiguously align the floor to a particular z-value in all cases, because some of our scenes have multiple walkable surfaces at different heights.

Fortunately, most of our floors are semantically labeled, so you could use either of the following strategies to estimate sensible z-coordinates for the floors:

- If you have access to the 3D meshes, you can use our mesh labels directly to determine the z-coordinates of all floor triangles.
- If you do not have access to the 3D meshes, then you can still use our rendered images to estimate the z-coordinates of the floors. You can interpret our world-space position images and our semantic segmentation images as forming a semantically labeled point cloud of the scene. Given such a point cloud, you can easily determine the z-coordinates of all floor points.

Once you have found an appropriate collection of floor primitives (either triangles or points) using either of these approaches, you could estimate a global z-coordinate for the floor, or you could find the closest primitive to each camera pose and use its z-coordinate if you'd rather compute a separate height estimate for each camera pose.
