### ISSUE TITLE
Questions about NaNs in depth_meter.hdf5

### ISSUE THREAD

**Issue by zzt76** [apple/ml-hypersim#63]
Hi,
I'm trying to load depth maps (or distance maps) from '*_geometry_hdf5/*depth_meter.hdf5'. However, I found out that there are some NaNs values in the depth maps. And here are a list of depth hdf5 files that contains NaNs values:
[depth_nan.txt](https://github.com/apple/ml-hypersim/files/13724585/depth_nan.txt)

Am I doing something wrong or is it normal that NaN values in depth map? If it's normal, what values should we use to replace the NaN values?

**Comment by mikeroberts3000** [comment]
It is expected that some pixels will have `nan` values for depth, because not all pixels contain actual scene geometry, e.g., background pixels. We assign the actual `nan` values here.

https://github.com/apple/ml-hypersim/main/code/python/tools/generate_hdf5_from_vrimg.py#L291

It is up to your application to decide what to do with these background pixels. In most learning applications, it seems like a sensible approach to mask them out and ignore them when computing a per-pixel loss.
