### ISSUE TITLE
Some case with error bounding box

### ISSUE THREAD

**Issue by SYSUykLin** [apple/ml-hypersim#79]
Hello:
     We found some bounding box placed error position in ai_015_003
![frame 0000 bb_object_aligned_2d](https://github.com/user-attachments/assets/a62f88d8-90fb-4ee3-b987-c80c0ea2c155)

How could I refine it? Thanks

**Comment by SYSUykLin** [comment]
Can I use this file? https://github.com/apple/ml-hypersim/tree/main/contrib/mikeroberts3000

**Comment by SYSUykLin** [comment]
I found that all the ai_018 have issues.

**Comment by SYSUykLin** [comment]
> Hi. Can you re-write your question in more detail? Please adhere to the usual recommendations for writing bug reports.
> 
> Additionally, the copy of `scene_generate_images_bounding_box.py` in this repo is 404 lines, and your error is on line 446, so it appears that you have made some undisclosed modifications to this file. Does your problem still happen when you're running an unmodified copy of `scene_generate_images_bounding_box.py`?

Very very sorry for my terrible expression. Firstly, let me express my apologies. 

Question:  
(1)  We found some pose problems frame 0 in ai_015_003. We run the unmodified version of “scene_generate_images_bounding_box.py”. It shows: 
![frame 0000 bb_object_aligned_2d](https://github.com/user-attachments/assets/965fab41-7044-45b7-9525-1480cfdf9cd1)

It didn't have any problems when runing code, but there was an error with the pose.
run:
```
python code/python/tools/unmodified_scene_generate_images_bounding_box.py --scene_dir Volumes\portable_hard_drive\evermotion_dataset\scenes/ai_015_003 --camera_name cam_00 --bounding_box_type object_aligned_2d --frame_id 0 --num_pixels_per_fragment 1
```
can reproduce the problem.

(2) In ai_018_*, the vast majority of scenes have encountered coding errors. 
![image](https://github.com/user-attachments/assets/6f63b6b0-5b64-4489-ba22-e1ef26f46a79)

The main reason is that there are no bounding boxes in the current frame(Generated 0 fragments), but there are actually objects in the frame. Therefore, I suspect that the projection method of the bounding box is incorrect. 

run:
```
python code/python/tools/unmodified_scene_generate_images_bounding_box.py --scene_dir Volumes\portable_hard_drive\evermotion_dataset\scenes/ai_018_003 --camera_name cam_00 --bounding_box_type object_aligned_2d --frame_id 0 --num_pixels_per_fragment 1
```
can reproduce the problem.

ai_018_* are great scene and I don't want to drop it, does any way to fix it? thanks. 
Very sorry for bother u many times. If there's anything you need me to add, please remind me. Thank you.

**Comment by mikeroberts3000** [comment]
Hi @SYSUykLin, thanks for your note.

I should mention that `scene_generate_images_bounding_box.py` was written as a quick-and-dirty script for generating a figure for our paper. We have not tested it on every scene. If you're using this code for large-scale learning or analysis, you will need to extend it to work more robustly for every scene. The snippets of code that need to be modified are clearly highlighted in the code comments. If you do modify the implementation to work more robustly, please submit a pull request.

The issue you're experiencing with `ai_015_003` appears to be due to the non-standard tilt-shift photography settings that affect some scenes, discussed [here](https://github.com/apple/ml-hypersim/tree/main/contrib/mikeroberts3000). The reason I think that is because when I visualize the bounding boxes using the `visualize_semantic_segmentation.py` script, I see bounding boxes that are well-aligned with the scene geometry. Notice the colors of the bounding boxes, because `scene_generate_images_bounding_box.py` uses the same colors for each object.

![image](https://github.com/user-attachments/assets/f216642f-2074-45d8-895a-5bc9fe14148e)

We can also verify that `ai_015_003` uses non-standard tilt-shift photography settings by examining `contrib/mikeroberts3000/metadata_camera_parameters.csv`. The tilt-shift photography settings that affect the camera intrinsics are labeled as `camera_physical_horizontal_offset`, `camera_physical_horizontal_shift`, `camera_physical_lens_shift`, and `camera_physical_vertical_offset` in this CSV file. In a typical scene, all of these parameters would be 0, but `camera_physical_lens_shift` is non-zero for this scene.

I believe the solution for this issue is to use the `M_proj` matrix defined in `metadata_camera_parameters.csv` instead of the one defined in `scene_generate_images_bounding_box.py`.

The issue with `ai_018_001` is easier to fix. When defining `M_proj`, `scene_generate_images_bounding_box.py` the near plane and far plane are hard-coded to be 1.0 and 1000.0 asset units away from the camera. This is a reasonable default for most scenes, but not for `ai_018_001`. This is because the scale of `ai_018_001` (in terms of asset units) is different from most scenes. We can verify this by examining the `meters_per_asset_unit` parameter in the `ai_018_001/_detail/metadata_scene.csv` file. A more sensible strategy would be for `scene_generate_images_bounding_box.py` would be to set near and far plane distances in terms of meters, rather than asset units, because there is less scale variation across scenes when working in meters. For this particular scene, I just set the near and far planes to be 10.0 and 10000.0, and I obtained the following image.

![frame 0000 bb_object_aligned_2d](https://github.com/user-attachments/assets/b532cafb-0d6a-47a8-8646-7c494a7b8890)

**Comment by SYSUykLin** [comment]
Thanks for your answer.

**Comment by SYSUykLin** [comment]
Hello, another question. If I use the https://github.com/apple/ml-hypersim/tree/main/contrib/mikeroberts3000 to generate the metadata_camera_parameters.csv, the program will be more robust, right?

On my god, I modify the scene_generate_images_bounding_box.py to generate a new dataset.

**Comment by SYSUykLin** [comment]
Hello, could you please tell me how many scenes have issues with non-standard tilt-shift photography settings?

**Comment by SYSUykLin** [comment]
hello, I want to rerun the scene which is non-standard tilt-shift photography settings. I used the method you mentioned to determine whether camera_physical_horizontal_offset, camera_physical_horizontal_shift, camera_physical_lens_shift, and camera_physical_vertical_offset  have at least one that is not 0. But I found there are some NaN value. 


Could you please tell me if there are any other ways to determine whether it is non-standard tilt-shift photography settings ?

**Comment by mikeroberts3000** [comment]
Have a look at `metadata_camera_parameters.csv`.

- If `use_camera_physical` is `False`, you don't need to do anything.
- If `use_camera_physical` is `True`, then `camera_physical_horizontal_offset`, `camera_physical_horizontal_shift`, `camera_physical_lens_shift`, and `camera_physical_vertical_offset` will be valid floating point numbers. If any of these numbers is non-zero, then you'll need to use the `M_proj` matrix defined in the CSV file.

Note that the `M_proj` matrix defined in the CSV file also assumes a near and far plane of 1.0 and 1000.0 asset units. This will be a problem if there is a scene that has non-standard tilt-shift camera parameters and an unusual scale in terms of asset units. You'll know if you encounter this case because bounding boxes for distant objects won't be generated, as you found with `ai_018_001`. But it's easy to re-compute `M_proj` with different clipping planes using the other data in the CSV file. Look at `contrib/mikeroberts3000/python/dataset_generate_camera_parameters_metadata.py` to see how `M_proj` is computed, and you'll notice you can can easily re-compute using the `M_cam_from_uv` matrix defined in the CSV file.

**Comment by SYSUykLin** [comment]
Thanks for your reply.  Happy Mid-Autumn Festival.

**Comment by SYSUykLin** [comment]
Sorry for bother u again. 
I try to run dataset_generate_camera_parameters_metadata.py. But I found I don't have vrscene file(maybe it need purchase).  Could u upload a metadata_camera_parameters.csv which assumes  a near and far plane of 1.0 and 50000.0 asset units?  Thanks

**Comment by mikeroberts3000** [comment]
No. I know you don't have the vrscene files necessary to re-run this code directly. Instead, look at how the code is implemented, look at how `M_proj` is computed, and then use the code as a starting point to write your own code to re-compute `M_proj` using whatever near and far plane you prefer. I promise you can re-compute it using data in the CSV file in a few lines of Python.

I'd also like to share some meta-feedback with you. Throughout this bug report, you have not invested much time into making it easy for me to help you. Your initial post was vague to the point of being nonsensical. Your second post was somewhat better, but still didn't describe your problem in a precise way, and it was a matter of luck that I could understand what you were saying in enough detail to even attempt to help you. (Saying "there was an error with the pose" is not helpful. There is an error with the pose of what? Why do you think there is an error? What exactly are your expectations, and what exactly is disagreeing with your expectations? What have you tried so far, so I don't have to spend my time trying things that you have already tried?) The solution to your follow-up issue with NaN values in the CSV file would have been obvious if you spent any time examining the CSV file yourself. And now you are literally asking me to write the code to solve your specific problem and send it to you. No.

As a rule of thumb, if you are asking someone to help you, and you think it will take them X units of time to do so, you should spend at least X units of time to make it as easy as possible for them. I will not be responding to further questions in this thread until you start engaging in a more productive way.

**Comment by SYSUykLin** [comment]
> No. I know you don't have the vrscene files necessary to re-run this code directly. Instead, you should look at how the code is implemented, and use it as a starting point to write your own code to re-compute `M_proj` using whatever near and far plane you prefer. I promise you can re-compute it using data in the CSV file in a few lines of Python.
> 
> I'll also take this opportunity to share some meta-feedback with you. Throughout this bug report, you have not invested much time into making it easy for me to help you. Your initial post was vague to the point of being nonsensical. Your second post was somewhat better, but still didn't describe your problem in a precise way, and it was a matter of luck that I could understand what you were saying in enough detail to even attempt to help you. (Saying "there was an error with the pose" is not helpful. There is an error with the pose of what exactly? Why do you think there is an error? What exactly are your expectations, and what exactly are you seeing that is disagreeing with your expectations? What have you tried so far, so I don't have to spend my time on things that you have already tried? What are the preceding steps that are working correctly, and why do you think they are working correctly, before something eventually stops working?) The solution to your follow-up issue with NaN values in the CSV file would have been obvious if you spent any time looking at the CSV file yourself. And now you are literally asking me to write the code to solve your very specific problem and send it to you. No.
> 
> As a rule of thumb, if you are asking someone to help you, and you think it will take them X units of time to do so, you should spend at least X units of time to make it as easy as possible for them. I will not be responding to further questions or comments in this thread until you adopt a more productive attitude.

Thanks for u reply. I apologize for my attitude, and I will check the files you mentioned myself. Thank you.
