### ISSUE TITLE
How to hypersim's Camera Pose to Blender Transform Matrix?

### ISSUE THREAD

**Issue by huntorochi** [apple/ml-hypersim#81]
Hi,

I am working with the provided camera pose data from the Hypersim dataset, specifically the files:

``
camera_positions_hdf5_file = os.path.join(camera_dir, "camera_keyframe_positions.hdf5")
camera_orientations_hdf5_file = os.path.join(camera_dir, "camera_keyframe_orientations.hdf5")

with h5py.File(camera_positions_hdf5_file, "r") as f:
camera_positions = f["dataset"][:]
with h5py.File(camera_orientations_hdf5_file, "r") as f:
camera_orientations = f["dataset"][:]

camera_position_world = camera_positions[frame_id]
R_world_from_cam = camera_orientations[frame_id]
``

From the above code, I understand that the dataset provides the camera's position (camera_position_world) and orientation (R_world_from_cam) in the 3ds Max coordinate system.

I need to convert this data into Blender's transform_matrix (4x4), considering the differences in the coordinate systems between 3ds Max and Blender.

Could you clarify the exact steps required to transform the provided position and rotation data into Blender's coordinate system? If possible, an example of the transformation process or the correct transformation matrix would be very helpful.

Thank you for your assistance!

**Comment by mikeroberts3000** [comment]
This question is out-of-scope. The Hypersim coordinate conventions are well-documented, and there is lots of example code in this repository showing how to visualize camera poses, how to project world-space points into images, and how to render images via raycasting. With all of this reference material in hand, it should be straightforward for you to figure out how to transcribe these coordinate conventions into your preferred DCC application (e.g., Blender, Maya, etc). Feel free to post a self-contained code snippet here when you figure it out.

**Comment by huntorochi** [comment]
Thank you for providing such an amazing dataset—it has been incredibly helpful for my research!

I’ve successfully converted the data into Blender coordinates for training purposes. However, I’m a bit confused regarding your comment in [https://github.com/apple/ml-hypersim/issues/29](url):

> But our asset coordinates are simply the world coordinates defined by the artist when they originally created the scenes in 3ds Max.

From my experience, I found that it is only when I do not include the 3ds Max to Blender transform matrix that the data works correctly for training with NeRF and 3D Gaussian Splatting. When I apply the transform matrix, the coordinates do not seem to align properly, which I do not fully understand.

Regardless, I’m happy that I was ultimately able to use the data successfully, and I truly appreciate the effort you’ve put into making this dataset available!
![00000](https://github.com/user-attachments/assets/0d8d5a20-ce91-49d2-8808-e1bec95ac3d6)
![00000](https://github.com/user-attachments/assets/739b5b29-b376-4e8a-9dbc-9e9fa2461368)

**Comment by mikeroberts3000** [comment]
> I’ve successfully converted the data into Blender coordinates for training purposes.

> From my experience, I found that it is only when I do not include the 3ds Max to Blender transform matrix that the data works correctly for training...

Which is it? These two sentences are saying the opposite things. Why do you think you've successfully converted to an alternative coordinate system if your code only works as you expect when you don't perform the conversion? You mention that you're confused by my previous comment, but you haven't explained what is confusing about it. I have no idea (because you haven't explained it) how my previous comment (the one that you find confusing) relates to the rest of your question.

> When I apply the transform matrix, the coordinates do not seem to align properly, which I do not fully understand.

I have no idea (because you haven't explained it) what you're trying to do. How could someone possibly help you based on the information you've provided? We never mention a "3ds Max to Blender transform matrix" in our documentation, so as far as I know, this is just a random undefined transformation you're applying somehow, to something, and your code isn't doing what you want. What does it mean for our data to "work correctly" during training? What does it mean for the "coordinates to align properly"? These vague sentences are completely undefined (except for in your mind) and could literally mean anything, and as a result it is impossible for my (or anyone) to help you.

I don't need you to answer these questions in a follow-up post. Questions about Blender and other random training code you found on the internet are out-of-scope for this repository. I'm highlighting them here because I want you to understand my specific points of confusion and imagine yourself as a reader that isn't familiar with your exact problem setup.

In general, you will get more effective help on GitHub and in other venues if you learn to ask questions more clearly. My main suggestion would be to slow down, and write out your questions in a more clear and methodical way. Your goal is to make your questions make sense to a reader that isn't familiar with your exact situation. This is a good example of how to report issues and ask questions on GitHub: https://github.com/facebookresearch/pytorch3d/issues/1255
